### ISSUE TITLE
Evaluation fails: Exception('Error: Invalid box type: %s' % box)

### ISSUE THREAD

**Issue by a1exr** [zhiqi-li/BEVFormer#45]
I'm trying to run the **evaluation** part based on the the provided checkpoints file
(./tools/dist_test.sh ./projects/configs/bevformer/bevformer_base.py ./ckpts/r101_dcn_fcos3d_pretrain.pth 1).
The bbox formating and annotations loading seem to work fine, but the evalution process stops due to a probelm in predictions filtering:

Formating bboxes of pts_bbox
Start to convert detection format...
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 6019/6019, 14298.1 task/s, elapsed: 0s, ETA:     0s
Results writes to test/bevformer_base/Mon_Jun_27_22_31_13_2022/pts_bbox/results_nusc.json
Evaluating bboxes of pts_bbox
======
Loading NuScenes tables for version v1.0-trainval...
23 category,
8 attribute,
4 visibility,
64386 instance,
12 sensor,
10200 calibrated_sensor,
2631083 ego_pose,
68 log,
850 scene,
34149 sample,
2631083 sample_data,
1166187 sample_annotation,
4 map,
Done loading in 30.495 seconds.
======
Reverse indexing ...
Done reverse indexing in 7.1 seconds.
======
Initializing nuScenes detection evaluation
Loaded results from test/bevformer_base/Mon_Jun_27_22_31_13_2022/pts_bbox/results_nusc.json. Found detections for 6019 samples.
Loading annotations for val split from nuScenes version: v1.0-trainval
100%|████████████████████████████████████████████████████████████████████████████████████| 6019/6019 [00:07<00:00, 835.78it/s]
Loaded ground truth annotations for 6019 samples.
Filtering predictions
Traceback (most recent call last):
  File "./tools/test.py", line 262, in <module>
    main()
  File "./tools/test.py", line 258, in main
    print(dataset.evaluate(outputs, **eval_kwargs))
  File "/home/eeproj4/Alex/mmdetection3d/mmdet3d/datasets/nuscenes_dataset.py", line 505, in evaluate
    ret_dict = self._evaluate_single(result_files[name])
  File "/home/eeproj4/Alex/mmdetection3d/BEVFormer/projects/mmdet3d_plugin/datasets/nuscenes_dataset.py", line 230, in _evaluate_single
    self.nusc_eval = NuScenesEval_custom(
  File "/home/eeproj4/Alex/mmdetection3d/BEVFormer/projects/mmdet3d_plugin/datasets/nuscnes_eval.py", line 570, in __init__
    self.pred_boxes = filter_eval_boxes(nusc, self.pred_boxes, self.cfg.class_range, verbose=verbose)
  File "/home/eeproj4/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/nuscenes/eval/common/loaders.py", line 219, in filter_eval_boxes
    class_field = _get_box_class_field(eval_boxes)
  File "/home/eeproj4/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/nuscenes/eval/common/loaders.py", line 283, in _get_box_class_field
    raise Exception('Error: Invalid box type: %s' % box)
Exception: Error: Invalid box type: None
Killing subprocess 490781
Traceback (most recent call last):
  File "/home/eeproj4/miniconda3/envs/open-mmlab/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/eeproj4/miniconda3/envs/open-mmlab/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/eeproj4/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/eeproj4/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/eeproj4/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/eeproj4/miniconda3/envs/open-mmlab/bin/python', '-u', './tools/test.py', '--local_rank=0', './projects/configs/bevformer/bevformer_base.py', './ckpts/r101_dcn_fcos3d_pretrain.pth', '--launcher', 'pytorch', '--eval', 'bbox']' returned non-zero exit status 1

Did anyone here encounter this problem and managed to solve it?
Many thanks

**Comment by zhiqi-li** [comment]
You should load the weight of [this](https://github.com/zhiqi-li/storage/releases/download/v1.0/bevformer_r101_dcn_24ep.pth) to eval.
