### ISSUE TITLE
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 32743) of binary

### ISSUE THREAD

**Issue by lvxuanxuan123** [zhiqi-li/BEVFormer#47]
hello! I replace "--eval bbox" with "--out ../test.pkl" in the file dist_test.sh。 and I use just 1 gpu to run test.py.

writing results to ../test.pkl
Traceback (most recent call last):
File "./tools/test.py", line 262, in <module>
    main()
  File "./tools/test.py", line 240, in main
    assert False
AssertionError
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 32743) of binary: /home/lxx/anaconda3/envs/bevformer/bin/python
ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed
INFO:torch.distributed.elastic.agent.server.api:[default] Worker group FAILED. 3/3 attempts left; will restart worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Stopping worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous'ing worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous complete for workers. Result:

**Comment by zhiqi-li** [comment]
BEVFormer will automatically save the result file during the eval phase. You do not need to replace "--eval bbox".

**Comment by lvxuanxuan123** [comment]
> 

so the --out  --show  --showdir config is invalid?

**Comment by lvxuanxuan123** [comment]
> > 
> 
> so the "--out"、" --show"、“ --show-dir” config is invalid? and by the way, what is the mean of the metric NDS?

**Comment by Alex-fishred** [comment]
![image](https://github.com/fundamentalvision/BEVFormer/assets/76515591/adbc8c99-8a30-4110-a176-5a4f68d11dab)
Solved my problem by using MMDataParallel and single_gpu_test
I use A6000 single GPU
