### ISSUE TITLE
Training error - Function not implemented: 'epoch_1.pth'

### ISSUE THREAD

**Issue by bobd988** [zhiqi-li/BEVFormer#50]
Hello,

When I ran training I got below error. I am running from Ubuntu 18.04 with 8 RTX A6000 and follow the instructions. This error happened after training for some time. Is there a way to work around this?

./tools/dist_train.sh ./projects/configs/bevformer/bevformer_base.py 8
.....

7020, d0.loss_cls: 0.3383, d0.loss_bbox: 0.7975, d1.loss_cls: 0.3330, d1.loss_bbox: 0.7195, d2.loss_cls: 0.3324, d2.loss_bbox: 0.7033, d3.loss_cls: 0.3333, d3.loss_bbox: 0.7003, d4.loss_cls: 0.3371, d4.loss_bbox: 0.7010, loss: 6.3380, grad_norm: 33.4391
2022-06-29 21:27:48,563 - mmdet - INFO - Saving checkpoint at 1 epochs
Traceback (most recent call last):
  File "./tools/train.py", line 259, in <module>
    main()
  File "./tools/train.py", line 248, in main
    custom_train_model(
  File "/media/dataset4/BEVFormer/projects/mmdet3d_plugin/bevformer/apis/train.py", line 26, in custom_train_model
    custom_train_detector(
  File "/media/dataset4/BEVFormer/projects/mmdet3d_plugin/bevformer/apis/mmdet_train.py", line 179, in custom_train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/user01/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/user01/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/home/user01/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/user01/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/hooks/checkpoint.py", line 116, in after_train_epoch
    self._save_checkpoint(runner)
  File "/home/user01/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/dist_utils.py", line 94, in wrapper
    return func(*args, **kwargs)
  File "/home/user01/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/hooks/checkpoint.py", line 121, in _save_checkpoint
    runner.save_checkpoint(
  File "/home/user01/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 175, in save_checkpoint
    mmcv.symlink(filename, dst_file)
  File "/home/user01/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/path.py", line 36, in symlink
    os.symlink(src, dst, **kwargs)
OSError: [Errno 38] Function not implemented: 'epoch_1.pth' -> '/media/dataset4/BEVFormer/work_dirs/bevformer_base/latest.pth'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1872990) of binary: /home/user01/anaconda3/envs/open-mmlab/bin/python
Traceback (most recent call last):
  File "/home/user01/anaconda3/envs/open-mmlab/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/user01/anaconda3/envs/open-mmlab/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user01/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/user01/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/user01/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/user01/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/distributed/run.py", line 689, in run
    elastic_launch(
  File "/home/user01/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/user01/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 244, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
***************************************
        ./tools/train.py FAILED

**Comment by zhiqi-li** [comment]
refer to this  https://github.com/open-mmlab/mmdetection/issues/3302
