### ISSUE TITLE
When I change the batch size, the following error occurs. prev_bev = torch.stack( RuntimeError: stack expects each tensor to be equal size, but got [2, 2500, 256] at entry 0 and [1, 2500, 256] at entry 1

### ISSUE THREAD

**Issue by MONSTER012** [zhiqi-li/BEVFormer#61]
#./tool/test.py
samples_per_gpu = args.batch_size
    if isinstance(cfg.data.test, dict):
        cfg.data.test.test_mode = True
        # samples_per_gpu =  cfg.data.test.pop('samples_per_gpu', samples_per_gpu)
        if samples_per_gpu > 1:
            # Replace 'ImageToTensor' to 'DefaultFormatBundle'
            cfg.data.test.pipeline = replace_ImageToTensor(
                cfg.data.test.pipeline)

Traceback (most recent call last):
  File "./tools/test.py", line 324, in <module>
    main()
  File "./tools/test.py", line 244, in main
    outputs = single_gpu_test(model, data_loader, scale, samples_per_gpu, args.show, args.show_dir)
  File "/home/lmh/BEVFormer/projects/mmdet3d_plugin/bevformer/apis/test.py", line 219, in single_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/home/lmh/.conda/envs/bevformer/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lmh/.conda/envs/bevformer/lib/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 50, in forward
    return super().forward(*inputs, **kwargs)
  File "/home/lmh/.conda/envs/bevformer/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/lmh/.conda/envs/bevformer/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lmh/BEVFormer/projects/mmdet3d_plugin/bevformer/detectors/bevformer.py", line 157, in forward
    return self.forward_test(**kwargs)
  File "/home/lmh/BEVFormer/projects/mmdet3d_plugin/bevformer/detectors/bevformer.py", line 260, in forward_test
    new_prev_bev, bbox_results = self.simple_test(
  File "/home/lmh/BEVFormer/projects/mmdet3d_plugin/bevformer/detectors/bevformer.py", line 285, in simple_test
    new_prev_bev, bbox_pts = self.simple_test_pts(
  File "/home/lmh/BEVFormer/projects/mmdet3d_plugin/bevformer/detectors/bevformer.py", line 270, in simple_test_pts
    outs = self.pts_bbox_head(x, img_metas, prev_bev=prev_bev)
  File "/home/lmh/.conda/envs/bevformer/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lmh/.conda/envs/bevformer/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 128, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/home/lmh/BEVFormer/projects/mmdet3d_plugin/bevformer/dense_heads/bevformer_head.py", line 169, in forward
    outputs = self.transformer(
  File "/home/lmh/.conda/envs/bevformer/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lmh/.conda/envs/bevformer/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 128, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/home/lmh/BEVFormer/projects/mmdet3d_plugin/bevformer/modules/transformer.py", line 252, in forward
    bev_embed = self.get_bev_features(
  File "/home/lmh/.conda/envs/bevformer/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 128, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/home/lmh/BEVFormer/projects/mmdet3d_plugin/bevformer/modules/transformer.py", line 186, in get_bev_features
    bev_embed = self.encoder(
  File "/home/lmh/.conda/envs/bevformer/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lmh/.conda/envs/bevformer/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 128, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/home/lmh/BEVFormer/projects/mmdet3d_plugin/bevformer/modules/encoder.py", line 203, in forward
    prev_bev = torch.stack(
RuntimeError: stack expects each tensor to be equal size, but got [2, 2500, 256] at entry 0 and [1, 2500, 256] at entry 1
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 35197) of binary: /home/lmh/.conda/envs/bevformer/bin/python

**Comment by zhiqi-li** [comment]
sorry for that, currently only batch_size=1 is supported in the inference phase.
