### ISSUE TITLE
_Z26ball_query_kernel_launcheriiiffiPKfS0_PiP11CUstream_st

### ISSUE THREAD

**Issue by WYYAHYT** [zhiqi-li/BEVFormer#88]
**Error like this:**
```
Traceback (most recent call last):
  File "tools/create_data.py", line 6, in <module>
    from data_converter.create_gt_database import create_groundtruth_database
  File "/data/run01/scz1974/zhangch/BEVFormer/tools/data_converter/create_gt_database.py", line 11, in <module>
    from mmdet3d.core.bbox import box_np_ops as box_np_ops
  File "/HOME/scz1974/.conda/envs/zhangch-BEVFormer/lib/python3.8/site-packages/mmdet3d-0.17.1-py3.8-linux-x86_64.egg/mmdet3d/core/__init__.py", line 3, in <module>
    from .bbox import *  # noqa: F401, F403
  File "/HOME/scz1974/.conda/envs/zhangch-BEVFormer/lib/python3.8/site-packages/mmdet3d-0.17.1-py3.8-linux-x86_64.egg/mmdet3d/core/bbox/__init__.py", line 5, in <module>
    from .iou_calculators import (AxisAlignedBboxOverlaps3D, BboxOverlaps3D,
  File "/HOME/scz1974/.conda/envs/zhangch-BEVFormer/lib/python3.8/site-packages/mmdet3d-0.17.1-py3.8-linux-x86_64.egg/mmdet3d/core/bbox/iou_calculators/__init__.py", line 2, in <module>
    from .iou3d_calculator import (AxisAlignedBboxOverlaps3D, BboxOverlaps3D,
  File "/HOME/scz1974/.conda/envs/zhangch-BEVFormer/lib/python3.8/site-packages/mmdet3d-0.17.1-py3.8-linux-x86_64.egg/mmdet3d/core/bbox/iou_calculators/iou3d_calculator.py", line 6, in <module>
    from ..structures import get_box_type
  File "/HOME/scz1974/.conda/envs/zhangch-BEVFormer/lib/python3.8/site-packages/mmdet3d-0.17.1-py3.8-linux-x86_64.egg/mmdet3d/core/bbox/structures/__init__.py", line 2, in <module>
    from .base_box3d import BaseInstance3DBoxes
  File "/HOME/scz1974/.conda/envs/zhangch-BEVFormer/lib/python3.8/site-packages/mmdet3d-0.17.1-py3.8-linux-x86_64.egg/mmdet3d/core/bbox/structures/base_box3d.py", line 6, in <module>
    from mmdet3d.ops.iou3d import iou3d_cuda
  File "/HOME/scz1974/.conda/envs/zhangch-BEVFormer/lib/python3.8/site-packages/mmdet3d-0.17.1-py3.8-linux-x86_64.egg/mmdet3d/ops/__init__.py", line 6, in <module>
    from .ball_query import ball_query
  File "/HOME/scz1974/.conda/envs/zhangch-BEVFormer/lib/python3.8/site-packages/mmdet3d-0.17.1-py3.8-linux-x86_64.egg/mmdet3d/ops/ball_query/__init__.py", line 1, in <module>
    from .ball_query import ball_query
  File "/HOME/scz1974/.conda/envs/zhangch-BEVFormer/lib/python3.8/site-packages/mmdet3d-0.17.1-py3.8-linux-x86_64.egg/mmdet3d/ops/ball_query/ball_query.py", line 4, in <module>
    from . import ball_query_ext
ImportError: /HOME/scz1974/.conda/envs/zhangch-BEVFormer/lib/python3.8/site-packages/mmdet3d-0.17.1-py3.8-linux-x86_64.egg/mmdet3d/ops/ball_query/ball_query_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _Z26ball_query_kernel_launcheriiiffiPKfS0_PiP11CUstream_st
```
Even can't google:
![image](https://user-images.githubusercontent.com/94819873/183091822-97cfe50a-0324-4a97-a2a6-13591ffefcb5.png)

**Comment by WYYAHYT** [comment]
**Really wish someone could help**

**Comment by zhiqi-li** [comment]
Hi, you can try to install mmcv  and mmdet3d from the source and make sure to use the same gcc  version.
